# Generated by Django 5.1 on 2024-10-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='name',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
